### ISSUE TITLE
axios update

### ISSUE THREAD

**Issue by Jsherborne92** [anttiviljami/openapi-client-axios#130]
Please update the axios peer dependency to the latest.

**Comment by anttiviljami** [comment]
Why? `^0.25.0` is fully compatible with latest

**Comment by jazmon** [comment]
Moro moro! 👀 Just to weigh in, I had to change axios version (to the semver-compatible one).
[Axios has released v1 now](https://github.com/axios/axios/blob/v1.x/CHANGELOG.md). 

In order to support the latest version, some things have to be fixed.
I ran into these before giving up and downgrading `axios`:
- https://github.com/axios/axios/issues/5142

and 

```
/[redacted]/.pnpm/axios@1.1.3/node_modules/axios/lib/core/dispatchRequest.js:17
  if (config.cancelToken) {
             ^
TypeError: Cannot read property 'cancelToken' of undefined
```

**Comment by Riglanto** [comment]
Any chance to get at least beta version wit axios 1+? In our case we've been using axios 1+ for some time, then added openapi-client-axios which is superb when working with external apis. We manage to make it work with 1+ and 0.25 in peer dependency leveraging `legacy-peer-deps` flag, but that leads to problems with prisma (that some deps/post-scripts are not run properly).

**Comment by anttiviljami** [comment]
Hi guys! `openapi-client-axios@6.0.0` is now out with support for axios v1. 🤝
