### ISSUE TITLE
Should I automatically see types when using JS?

### ISSUE THREAD

**Issue by goldbergyoni** [anttiviljami/openapi-client-axios#78]
Great initiate here, thank you.

Question - I'm using JS and followed the docs, but can't see any types suggestion in vscode. Here what I've done:

```
const mailerAPI = new OpenAPIClientAxios({
    definition: path.join(__dirname, '../openapi.json'),
  });
  await mailerAPI.init();
  mailerAPI.{expected to see methods here but nothing from openapi operations appear here}
```

Should I run typegen manually? What is the workflow for JS scenario (not TS) given that most IDE knows to conclude d.ts file definitions even when coding with JS?

**Comment by TomFrost** [comment]
Hi @goldbergyoni -- I'm not the maintainer but I figured I'd answer since I just did this myself.

You _do_ need to run typegen yourself, and store the file somewhere it's accessible to your source code.

Then your snippet becomes this:

```typescript
import { Client as MyApiClient } from './path/to/generated/typefile'

const clientGenerator = new OpenAPIClientAxios({
  definition: path.join(__dirname, '../openapi.json'),
});
const mailerAPI = await clientGenerator.getClient<MyApiClient>();
mailerAPI.{now you see methods here}
```

The constructor for the main class can't be typed with your custom types, unfortunately. Even if you pass it when you call init(), that custom typing won't be saved that way. The answer is to keep a reference to the instance it returns, which _is_ associated with your custom types.

`getClient()` is the better way to go than `init()`, though, because it still calls `init` under the hood for an instance that hasn't been initialized yet, but the returned instance is a singleton -- so if you ever call it again, you're getting the same object back without re-initializing.

Hope this helps!

**Comment by npdev453** [comment]
@goldbergyoni,
you should give a help to you hinting tool how to resolve client type. 


Example using `jsDoc`: 

```pet.types``` is ```pet.types.d.ts``` generated by `typegen` tool
```example.js```
``` js 
import { OpenAPIClientAxios } from './openapi-client-axios'

/** @type {() => import("./pet.types").Client } **/
const getMyOACA = () => {
    const clientInstance = new OpenAPIClientAxios();
    return clientInstance;
}

const client = getMyOACA();
client.updatePetById()
```

and hints il work

![image](https://user-images.githubusercontent.com/1401931/148386445-ba711b67-80d0-4f61-933e-47f5c0865d65.png)
