### ISSUE TITLE
Next Release/Release Cycle?

### ISSUE THREAD

**Issue by nathanielford** [anttiviljami/openapi-client-axios#99]
Heya!

I was looking for information about the release cycle of this library. This is a motivated question, as I'd love a release with [this commit](https://github.com/anttiviljami/openapi-client-axios/commit/88c2309bd57919ec3c017ef620c40a71217b3b71) available, but in general I was curious if there was a set release cycle, and if not, could some guideline be established in one of the doc files? I want to avoid asking this sort of question if I can find the information myself, so as not to pester maintainers. 

Thank you for your attention! Cheers!

**Comment by anttiviljami** [comment]
Hi @nathanielford !

For a release cycle / guideline, there is none. I'm currently the sole maintainer of this project and so far there is no interest I'm aware of from 3rd parties to support / take over the maintainership.

Looks like I'll continue doing the releases whenever I feel like it or otherwise need to for my own work. 

P.S. You'll be happy to hear I've just released `openapi-client-axios@4.6.0` ! :)

**Comment by nathanielford** [comment]
Thanks for the response! I totally get the single-dev burden! And I also wicked appreciate the release! Thanks again!
